# Generated by Django 5.2.8 on 2025-12-05 19:17

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destekci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Destekçi Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta Adresi')),
                ('paket', models.CharField(choices=[('okur', 'Okur Desteği (250 TL)'), ('gonul', 'Gönül Dostu (500 TL)'), ('sponsor', 'Sponsor (1.000 TL)')], default='okur', max_length=10, verbose_name='Abonelik Paketi')),
                ('baslangic_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abonelik Başlangıcı')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Bitişi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Abone',
                'verbose_name_plural': 'Aboneler',
            },
        ),
        migrations.CreateModel(
            name='EczaneLinki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=100, verbose_name='İlçe Adı (Örn: Hopa)')),
                ('url', models.URLField(max_length=500, verbose_name='Eczane Listesi Linki')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name_plural': 'Nöbetçi Eczane Linkleri',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Galeri Başlığı')),
                ('kapak_resmi', models.ImageField(upload_to='galeri_kapak/', verbose_name='Kapak Resmi')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Foto Galerileri',
            },
        ),
        migrations.CreateModel(
            name='HaftaninFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Fotoğraf Adı')),
                ('fotografci', models.CharField(max_length=100, verbose_name='Fotoğrafçı')),
                ('resim', models.ImageField(upload_to='haftanin_fotografi/', verbose_name='Fotoğraf Dosyası')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Sitede Göster')),
            ],
            options={
                'verbose_name_plural': 'Haftanın Fotoğrafları',
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İlçe Adı')),
            ],
            options={
                'verbose_name_plural': 'İlçeler',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='KoseYazari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Yazar Adı Soyadı')),
                ('resim', models.ImageField(upload_to='yazar_resimleri/', verbose_name='Yazar Resmi (Kare)')),
                ('basyazar_mi', models.BooleanField(default=False, verbose_name='Başyazar mı? (En başa sabitler)')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Sitede Göster')),
            ],
            options={
                'verbose_name': 'Köşe Yazarı',
                'verbose_name_plural': 'Köşe Yazarları',
            },
        ),
        migrations.CreateModel(
            name='Siir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Şiir Başlığı')),
                ('sair', models.CharField(max_length=100, verbose_name='Şair')),
                ('siir_metni', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Şiir Metni')),
                ('resim', models.ImageField(blank=True, upload_to='siir_resimleri/', verbose_name='Şiir Görseli')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Şiir',
                'verbose_name_plural': 'Şiir Köşesi',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GaleriResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='galeri_resimleri/')),
                ('alt_yazi', models.CharField(blank=True, max_length=200, verbose_name='Alt Yazı (Opsiyonel)')),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='haberler.galeri')),
            ],
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('ozet', models.TextField(blank=True, verbose_name='Kısa Özet')),
                ('icerik', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Haber İçeriği')),
                ('resim', models.ImageField(blank=True, upload_to='haber_resimleri/', verbose_name='Haber Resmi')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('manset_mi', models.BooleanField(default=False, verbose_name='Manşette Göster')),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.ilce', verbose_name='İlçe (Varsa)')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.kategori', verbose_name='Kategori')),
                ('yazar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.koseyazari', verbose_name='Haberin Yazarı')),
            ],
            options={
                'verbose_name_plural': 'Haberler',
            },
        ),
        migrations.CreateModel(
            name='KoseYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Yazı Başlığı')),
                ('icerik', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yazı İçeriği')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to='haberler.koseyazari', verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Köşe Yazısı',
                'verbose_name_plural': 'Köşe Yazıları',
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('govde', models.TextField(verbose_name='Yorumunuz')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('aktif', models.BooleanField(default=False, verbose_name='Yayınlansın mı?')),
                ('haber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.haber', verbose_name='Haber')),
                ('kose_yazisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.koseyazisi', verbose_name='Köşe Yazısı')),
                ('siir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.siir', verbose_name='Şiir')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
