# Generated by Django 5.2.8 on 2025-12-01 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('ozet', models.TextField(blank=True, verbose_name='Kısa Özet')),
                ('icerik', models.TextField(verbose_name='Haber İçeriği')),
                ('resim', models.ImageField(blank=True, upload_to='haber_resimleri/', verbose_name='Haber Resmi')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
            },
        ),
    ]
