# Generated by Django 5.2.8 on 2025-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='video_link',
            field=models.URLField(blank=True, help_text='Örn: https://www.youtube.com/watch?v=VIDEO_ID', null=True, verbose_name='Video Linki (YouTube)'),
        ),
        migrations.AddField(
            model_name='koseyazisi',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video Linki (YouTube)'),
        ),
    ]
