# Generated by Django 5.2.8 on 2025-12-01 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=ckeditor.fields.RichTextField(verbose_name='Haber İçeriği'),
        ),
    ]
