# Generated by Django 5.2.8 on 2025-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_alter_haber_icerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='manset_mi',
            field=models.BooleanField(default=False, verbose_name='Manşette Göster'),
        ),
    ]
