# Generated by Django 5.2.8 on 2025-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_haber_video_link_koseyazisi_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='son_dakika',
            field=models.BooleanField(default=False, verbose_name='Son Dakika Haberi mi?'),
        ),
    ]
