# Generated by Django 5.2.8 on 2025-12-03 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_haber_manset_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Galeri Başlığı')),
                ('kapak_resmi', models.ImageField(upload_to='galeri_kapak/', verbose_name='Kapak Resmi')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Foto Galerileri',
            },
        ),
        migrations.CreateModel(
            name='HaftaninFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Fotoğraf Adı')),
                ('fotografci', models.CharField(max_length=100, verbose_name='Fotoğrafçı')),
                ('resim', models.ImageField(upload_to='haftanin_fotografi/', verbose_name='Fotoğraf Dosyası')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Sitede Göster')),
            ],
            options={
                'verbose_name': 'Haftanın Fotoğrafı',
                'verbose_name_plural': 'Haftanın Fotoğrafları',
            },
        ),
        migrations.CreateModel(
            name='GaleriResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='galeri_resimleri/')),
                ('alt_yazi', models.CharField(blank=True, max_length=200, verbose_name='Alt Yazı (Opsiyonel)')),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='haberler.galeri')),
            ],
        ),
    ]
