# Generated by Django 5.2.8 on 2025-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_haber_son_dakika'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siir',
            options={'ordering': ['-yayin_tarihi'], 'verbose_name_plural': 'Şiir Köşesi'},
        ),
        migrations.AlterModelOptions(
            name='yorum',
            options={'ordering': ['-olusturulma_tarihi']},
        ),
        migrations.AddField(
            model_name='haber',
            name='ulusal_mi',
            field=models.BooleanField(default=False, verbose_name='Ulusal Haber mi? (Tikli değilse Yereldir)'),
        ),
    ]
