# Generated by Django 5.2.8 on 2025-12-07 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0004_alter_siir_options_alter_yorum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koseyazisi',
            options={'ordering': ['-yayin_tarihi'], 'verbose_name_plural': 'Köşe Yazıları'},
        ),
        migrations.AddField(
            model_name='koseyazisi',
            name='manset_mi',
            field=models.BooleanField(default=False, verbose_name='Manşette Gösterilsin mi?'),
        ),
        migrations.AddField(
            model_name='koseyazisi',
            name='manset_resmi',
            field=models.ImageField(blank=True, help_text='Eğer manşete koyacaksanız mutlaka yatay bir resim yükleyin.', null=True, upload_to='manset_yazilari/', verbose_name='Manşet Görseli (Yatay)'),
        ),
        migrations.AlterField(
            model_name='koseyazisi',
            name='yayin_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
