# Generated by Django 5.2.8 on 2025-12-03 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0004_galeri_haftaninfotografi_galeriresim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İlçe Adı')),
            ],
            options={
                'verbose_name_plural': 'İlçeler',
            },
        ),
        migrations.RemoveField(
            model_name='haber',
            name='icerik',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='ozet',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='resim',
        ),
        migrations.AlterField(
            model_name='haber',
            name='yayin_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi'),
        ),
        migrations.AddField(
            model_name='haber',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.ilce', verbose_name='İlçe (Varsa)'),
        ),
    ]
