# Generated by Django 5.2.8 on 2025-12-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_alter_koseyazisi_options_koseyazisi_manset_mi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzelGun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Özel Gün Adı (Örn: 2025 Yılbaşı)')),
                ('slug', models.SlugField(unique=True, verbose_name='Link Uzantısı (Otomatik)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Sayfa Üst Yazısı')),
                ('kapak_resmi', models.ImageField(blank=True, upload_to='ozel_gunler/', verbose_name='Sayfa Kapak Resmi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('anasayfada_goster', models.BooleanField(default=False, verbose_name='Anasayfada Slayt Olarak Göster')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Özel Gün Yönetimi',
            },
        ),
        migrations.CreateModel(
            name='TebrikMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Kişi / Kurum Adı')),
                ('unvan', models.CharField(blank=True, max_length=150, verbose_name='Ünvanı (Örn: Artvin Valisi)')),
                ('mesaj_metni', models.TextField(blank=True, verbose_name='Mesajı')),
                ('resim', models.ImageField(upload_to='tebrikler/', verbose_name='Kişi Fotoğrafı')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video Linki (Varsa)')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama (Küçük sayı önde)')),
                ('ozel_gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='haberler.ozelgun')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
    ]
