# Generated by Django 5.2.8 on 2025-12-03 17:19

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_ilce_remove_haber_icerik_remove_haber_ozet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Foto Galerileri'},
        ),
        migrations.AlterModelOptions(
            name='haber',
            options={'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='haftaninfotografi',
            options={'verbose_name_plural': 'Haftanın Fotoğrafları'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='haber',
            name='icerik',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Haber İçeriği'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haber',
            name='ozet',
            field=models.TextField(blank=True, verbose_name='Kısa Özet'),
        ),
        migrations.AddField(
            model_name='haber',
            name='resim',
            field=models.ImageField(blank=True, upload_to='haber_resimleri/', verbose_name='Haber Resmi'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='yayin_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
