# Generated by Django 5.2.8 on 2025-12-04 18:04

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0006_alter_galeri_options_alter_haber_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EczaneLinki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=100, verbose_name='İlçe Adı (Örn: Hopa)')),
                ('url', models.URLField(max_length=500, verbose_name='Eczane Listesi Linki')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name_plural': 'Nöbetçi Eczane Linkleri',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='KoseYazari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Yazar Adı Soyadı')),
                ('resim', models.ImageField(upload_to='yazar_resimleri/', verbose_name='Yazar Resmi (Kare)')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Sitede Göster')),
            ],
            options={
                'verbose_name': 'Köşe Yazarı',
                'verbose_name_plural': 'Köşe Yazarları',
            },
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Haber İçeriği'),
        ),
        migrations.CreateModel(
            name='KoseYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Yazı Başlığı')),
                ('icerik', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yazı İçeriği')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to='haberler.koseyazari', verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Köşe Yazısı',
                'verbose_name_plural': 'Köşe Yazıları',
            },
        ),
    ]
