# Generated by Django 5.2.8 on 2025-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0006_ozelgun_tebrikmesaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebrikmesaji',
            name='instagram_gorseli',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_postlari/', verbose_name='Hazır Instagram Postu'),
        ),
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='unvan',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ünvanı'),
        ),
    ]
