# Generated by Django 5.2.8 on 2025-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_tebrikmesaji_instagram_gorseli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='instagram_gorseli',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_postlari/', verbose_name='Hazır Post'),
        ),
    ]
