# Generated by Django 5.2.8 on 2025-12-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_eczanelinki_koseyazari_alter_haber_icerik_koseyazisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('govde', models.TextField(verbose_name='Yorumunuz')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('aktif', models.BooleanField(default=False, verbose_name='Yayınlansın mı?')),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.haber', verbose_name='Haber')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
