# Generated by Django 5.2.8 on 2025-12-07 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0008_alter_tebrikmesaji_instagram_gorseli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destekci',
            options={'verbose_name_plural': 'Aboneler ve Destekçiler'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Fotoğraf Galerileri'},
        ),
        migrations.AlterModelOptions(
            name='haber',
            options={'ordering': ['-yayin_tarihi'], 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='haftaninfotografi',
            options={'verbose_name_plural': 'Haftanın Fotoğrafı'},
        ),
        migrations.AlterModelOptions(
            name='koseyazari',
            options={'verbose_name_plural': 'Köşe Yazarları'},
        ),
        migrations.RemoveField(
            model_name='galeriresim',
            name='alt_yazi',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='yazar',
        ),
        migrations.RemoveField(
            model_name='haftaninfotografi',
            name='fotografci',
        ),
        migrations.AddField(
            model_name='galeriresim',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resim Açıklaması (Opsiyonel)'),
        ),
        migrations.AddField(
            model_name='haftaninfotografi',
            name='ceken',
            field=models.CharField(default='Artvizyon', max_length=100, verbose_name='Fotoğrafı Çeken'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Link Uzantısı'),
        ),
        migrations.AddField(
            model_name='koseyazari',
            name='biyografi',
            field=models.TextField(blank=True, verbose_name='Kısa Biyografi'),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='aktif_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='baslangic_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destek Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Destekçi Adı / Firma'),
        ),
        migrations.AlterField(
            model_name='destekci',
            name='paket',
            field=models.CharField(choices=[('okur', 'Okur Destekçisi'), ('gonul', 'Gönül Dostu'), ('sponsor', 'Ana Sponsor')], default='okur', max_length=20),
        ),
        migrations.AlterField(
            model_name='eczanelinki',
            name='ilce_adi',
            field=models.CharField(max_length=50, verbose_name='İlçe Adı (Örn: Hopa)'),
        ),
        migrations.AlterField(
            model_name='eczanelinki',
            name='sira',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eczanelinki',
            name='url',
            field=models.URLField(verbose_name='Eczane Listesi Linki'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='yayin_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='haber',
            name='ulusal_mi',
            field=models.BooleanField(default=False, verbose_name='Ulusal Haber mi?'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video Linki (YouTube)'),
        ),
        migrations.AlterField(
            model_name='haftaninfotografi',
            name='aktif_mi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='haftaninfotografi',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık / Açıklama'),
        ),
        migrations.AlterField(
            model_name='haftaninfotografi',
            name='resim',
            field=models.ImageField(upload_to='haftanin_fotografi/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='koseyazari',
            name='ad_soyad',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='koseyazari',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='koseyazari',
            name='basyazar_mi',
            field=models.BooleanField(default=False, verbose_name='Başyazar mı?'),
        ),
        migrations.AlterField(
            model_name='koseyazari',
            name='resim',
            field=models.ImageField(upload_to='yazarlar/', verbose_name='Yazar Resmi'),
        ),
        migrations.AlterField(
            model_name='koseyazisi',
            name='manset_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='manset_yazilari/', verbose_name='Manşet Görseli (Yatay)'),
        ),
        migrations.AlterField(
            model_name='ozelgun',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Sayfa Üst Yazısı / Artvizyon Mesajı'),
        ),
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='instagram_gorseli',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_postlari/', verbose_name='Hazır Instagram Postu'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='haber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.haber'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='kose_yazisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.koseyazisi'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='siir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.siir'),
        ),
    ]
