# Generated by Django 5.2.8 on 2025-12-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0008_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='kose_yazisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.koseyazisi', verbose_name='Köşe Yazısı'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='haber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.haber', verbose_name='Haber'),
        ),
    ]
