# Generated by Django 5.2.8 on 2025-12-04 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0009_yorum_kose_yazisi_alter_yorum_haber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destekci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Destekçi Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta Adresi (Yorumlarla Eşleşmesi İçin)')),
                ('paket', models.CharField(choices=[('okur', 'Okur Desteği (250 TL)'), ('gonul', 'Gönül Dostu (500 TL)'), ('sponsor', 'Sponsor (1.000 TL)')], default='okur', max_length=10, verbose_name='Abonelik Paketi')),
                ('baslangic_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abonelik Başlangıcı')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Bitişi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Abone',
                'verbose_name_plural': 'Aboneler',
            },
        ),
    ]
