# Generated by Django 5.2.8 on 2025-12-08 20:08

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0009_alter_destekci_options_alter_galeri_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='kapak_resmi',
            field=imagekit.models.fields.ProcessedImageField(upload_to='galeri_kapak/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='galeriresim',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(upload_to='galeri_resimleri/'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='haber_resimleri/', verbose_name='Haber Resmi'),
        ),
        migrations.AlterField(
            model_name='haftaninfotografi',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(upload_to='haftanin_fotografi/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='koseyazari',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(upload_to='yazarlar/', verbose_name='Yazar Resmi'),
        ),
        migrations.AlterField(
            model_name='koseyazisi',
            name='manset_resmi',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='manset_yazilari/', verbose_name='Manşet Görseli (Yatay)'),
        ),
        migrations.AlterField(
            model_name='ozelgun',
            name='kapak_resmi',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='ozel_gunler/', verbose_name='Sayfa Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='siir',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='siir_resimleri/', verbose_name='Şiir Görseli'),
        ),
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='instagram_gorseli',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_postlari/', verbose_name='Hazır Post'),
        ),
        migrations.AlterField(
            model_name='tebrikmesaji',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(upload_to='tebrikler/', verbose_name='Kişi Fotoğrafı'),
        ),
    ]
