# Generated by Django 5.2.8 on 2025-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0010_alter_galeri_kapak_resmi_alter_galeriresim_resim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siir',
            name='gunun_siiri_mi',
            field=models.BooleanField(default=False, verbose_name='Günün Şiiri Olarak Ayarla'),
        ),
    ]
