# Generated by Django 5.2.8 on 2025-12-10 14:35

import ckeditor_uploader.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0011_siir_gunun_siiri_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarihiYer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Yer Adı (Örn: Artvin Kalesi)')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Link Uzantısı')),
                ('ozet', models.TextField(blank=True, verbose_name='Kısa Tanıtım (Listede görünür)')),
                ('icerik', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detaylı Bilgi')),
                ('resim', imagekit.models.fields.ProcessedImageField(upload_to='tarihi_yerler/', verbose_name='Kapak Fotoğrafı')),
                ('harita_konumu', models.CharField(blank=True, max_length=500, verbose_name='Google Maps Embed Linki (İsteğe Bağlı)')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama (Önce çıkması için)')),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tarihi ve Turistik Yerler',
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='haber',
            name='foto_kaynak',
            field=models.CharField(blank=True, help_text="Boş bırakırsan 'Artvizyon Haber' yazar.", max_length=100, verbose_name='Fotoğraf Kaynağı (Örn: AA, İHA)'),
        ),
        migrations.AddField(
            model_name='haber',
            name='roportaj_mi',
            field=models.BooleanField(default=False, verbose_name='Bu Bir Röportaj mı?'),
        ),
    ]
