# Generated by Django 5.2.8 on 2025-12-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0012_tarihiyer_haber_foto_kaynak_haber_roportaj_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarihiyer',
            name='boylam',
            field=models.CharField(blank=True, help_text='Örn: 41.8183', max_length=50, null=True, verbose_name='Boylam (Longitude)'),
        ),
        migrations.AddField(
            model_name='tarihiyer',
            name='enlem',
            field=models.CharField(blank=True, help_text='Örn: 41.1828', max_length=50, null=True, verbose_name='Enlem (Latitude)'),
        ),
    ]
