# Generated by Django 5.2.8 on 2025-12-10 17:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0013_tarihiyer_boylam_tarihiyer_enlem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarihiyer',
            name='harita_ikonu',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Arka planı şeffaf, izometrik/3D görünümlü bir PNG yükleyin.', null=True, upload_to='harita_ikonlari/', verbose_name='Harita İkonu (3D Görünümlü PNG)'),
        ),
    ]
