# Generated by Django 5.2.8 on 2025-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0014_tarihiyer_harita_ikonu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarihiyer',
            name='ilce',
            field=models.CharField(choices=[('Merkez', 'Merkez'), ('Arhavi', 'Arhavi'), ('Borçka', 'Borçka'), ('Hopa', 'Hopa'), ('Şavşat', 'Şavşat'), ('Yusufeli', 'Yusufeli'), ('Ardanuç', 'Ardanuç'), ('Murgul', 'Murgul'), ('Kemalpaşa', 'Kemalpaşa')], default='Merkez', max_length=50, verbose_name='Bulunduğu İlçe'),
        ),
    ]
