# Generated by Django 5.2.8 on 2025-12-10 19:20

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0015_tarihiyer_ilce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profil_resimleri/', verbose_name='Profil Resmi')),
                ('telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası')),
                ('biyografi', models.TextField(blank=True, max_length=500, verbose_name='Kısa Biyografi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
