# Generated by Django 5.2.8 on 2025-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0016_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='koseyazisi',
            name='foto_kaynak',
            field=models.CharField(blank=True, help_text='Örn: AA, Anadolu Ajansı, Artvizyon Arşiv. Zorunlu değildir.', max_length=150, null=True, verbose_name='Fotoğraf Kaynağı'),
        ),
        migrations.AddField(
            model_name='siir',
            name='foto_kaynak',
            field=models.CharField(blank=True, help_text='Örn: AA, Anadolu Ajansı, Artvizyon Arşiv. Zorunlu değildir.', max_length=150, null=True, verbose_name='Fotoğraf Kaynağı'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='foto_kaynak',
            field=models.CharField(blank=True, help_text='Örn: AA, Anadolu Ajansı, Artvizyon Arşiv. Zorunlu değildir.', max_length=150, null=True, verbose_name='Fotoğraf Kaynağı'),
        ),
    ]
