# Generated by Django 5.2.8 on 2025-12-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0017_koseyazisi_foto_kaynak_siir_foto_kaynak_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yorum',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
