# Generated by Django 5.2.8 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0018_alter_yorum_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HaftaninFotografi',
        ),
        migrations.AddField(
            model_name='galeriresim',
            name='haftanin_fotografi_mi',
            field=models.BooleanField(default=False, verbose_name='Haftanın Fotoğrafı'),
        ),
    ]
