# Generated by Django 5.2.8 on 2026-01-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0020_yazarlar_siir_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='okunma_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Okunma Sayısı'),
        ),
        migrations.AddField(
            model_name='koseyazisi',
            name='okunma_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Okunma Sayısı'),
        ),
        migrations.AddField(
            model_name='siir',
            name='okunma_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Okunma Sayısı'),
        ),
    ]
