"""
Django settings for artvinvizyonu project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-s^$-b*^=_bn2#npf-#=mlby5x2u@p0mp7fpnk&==wxntuq(e#8'
DEBUG = True 

# PythonAnywhere için izin verilen adresler
ALLOWED_HOSTS = ['*'] 


# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'reversion',
    'imagekit', 
    'haberler', 
    'ckeditor',
    'ckeditor_uploader',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # ------------------------------------------------
    # --- ALLAUTH MIDDLEWARE'İ BURAYA EKLE (ÇOK ÖNEMLİ) ---
    'allauth.account.middleware.AccountMiddleware',
    # ------------------------------------------------
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'artvinvizyonu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom Context Processor
                'haberler.views.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'artvinvizyonu.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- JAZZMIN AYARLARI (MEVCUT) ---
JAZZMIN_SETTINGS = {
    "site_title": "Artvizyon Yönetim",
    "site_header": "Artvizyon",
    "site_brand": "Artvizyon Haber Yönetim",
    "welcome_sign": "Hoş Geldiniz, Artvizyon Yönetim Paneli",
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Anasayfa",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Siteyi Gör", "url": "/"},
    ],
    "order_with_respect_to": ["haberler.haber", "haberler.koseyazisi", "haberler.koseyazari", "haberler.kategori", "haberler.ilce", "haberler.galeri"],
    "icons": {
        "auth.user": "fas fa-user-circle",
        "auth.Group": "fas fa-users",
        "haberler.haber": "fas fa-newspaper",
        "haberler.koseyazisi": "fas fa-pencil-alt",
        "haberler.koseyazari": "fas fa-quidditch",
        "haberler.kategori": "fas fa-tags",
        "haberler.ilce": "fas fa-city",
        "haberler.galeri": "fas fa-images",
        "haberler.yorum": "fas fa-comment-dots",
        "haberler.destekci": "fas fa-hand-holding-heart",
        "haberler.siir": "fas fa-feather",
        "haberler.ozelgun": "fas fa-calendar-day",
        "haberler.tebrikmesaji": "fas fa-birthday-cake",
        "haberler.tarihiyer": "fas fa-map-marker-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "theme": "united",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# --- GİRİŞ / ÇIKIŞ AYARLARI (HATA ÇÖZÜMÜ BURADA) ---
# Django'nun login URL'ini allauth'un login URL'ine yönlendiriyoruz
# 'login' yerine 'account_login' kullanarak NoReverseMatch hatasını çözüyoruz.
LOGIN_URL = 'account_login' 
# Giriş/Çıkış sonrası yönlendirme anasayfa
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'


# MEDYA AYARLARI (Resim/Video için)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CKEDITOR AYARLARI (Video Dostu Versiyon)
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 500,
        'width': '100%',
        # BU İKİ SATIR VİDEOLAR İÇİN HAYATİ:
        'allowedContent': True,
        'removePlugins': 'stylesheetparser',
        'extraAllowedContent': 'iframe[*];script[*];div[*]',
    },
}

# GÜVENLİK DUVARLARINI VİDEOLAR İÇİN İPTAL EDEN AYARLAR
X_FRAME_OPTIONS = 'SAMEORIGIN'


# ------------------------------------------------
# --- DJANGO-ALLAUTH SOSYAL GİRİŞ AYARLARI ---
# ------------------------------------------------

# Allauth'a Django'nun Authentication Backend'ini kullanmasını söyler
AUTHENTICATION_BACKENDS = (
    # Sosyal hesaplar için gerekli (Üstte olmalı)
    'allauth.account.auth_backends.AuthenticationBackend', 
    # Django'nun standart kimlik doğrulama yöntemi
    'django.contrib.auth.backends.ModelBackend',
)

# Allauth için Site ID'si (Admin panelindeki Sites tablosundan gelen ID)
SITE_ID = 1 

# Allauth ayarları
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_SIGNUP_NO_FIELDS = True

# settings.py dosyasının en altına ekle:

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'EMAIL_AUTHENTICATION': True,
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}

# Opsiyonel: SocialApp modeline eklemeden Google/Facebook OAuth bilgilerini
# ortam değişkenlerinden tanımlayabilmek için destekle.
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
if GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS['google']['APP'] = {
        'client_id': GOOGLE_CLIENT_ID,
        'secret': GOOGLE_CLIENT_SECRET,
        'key': os.getenv('GOOGLE_CLIENT_KEY', ''),
    }

FACEBOOK_CLIENT_ID = os.getenv('FACEBOOK_CLIENT_ID') or os.getenv('FACEBOOK_APP_ID')
FACEBOOK_CLIENT_SECRET = os.getenv('FACEBOOK_CLIENT_SECRET') or os.getenv('FACEBOOK_APP_SECRET')
if FACEBOOK_CLIENT_ID and FACEBOOK_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS['facebook']['APP'] = {
        'client_id': FACEBOOK_CLIENT_ID,
        'secret': FACEBOOK_CLIENT_SECRET,
        'key': os.getenv('FACEBOOK_CLIENT_KEY', ''),
    }
