"""
Django settings for artvinvizyonu project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os # <-- Bunu ekledik, sistem işlemleri için lazım

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s^$-b*^=_bn2#npf-#=mlby5x2u@p0mp7fpnk&==wxntuq(e#8'

# SECURITY WARNING: don't run with debug turned on in production!
# Canlıya aldıktan sonra her şey tamamsa bunu False yapabilirsin.
DEBUG = True 

# DİKKAT: Canlı sunucuda çalışması için burayı ['*'] yaptık.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin', # Admin paneli teması (En üstte olmalı)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haberler', # Senin uygulaman
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'artvinvizyonu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'haberler.context_processors.global_veriler', # Menülerin çalışması için (Eğer dosya adın farklıysa düzelt)
            ],
        },
    },
]

WSGI_APPLICATION = 'artvinvizyonu.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
LANGUAGE_CODE = 'tr' # Türkçe yaptık

TIME_ZONE = 'Europe/Istanbul' # Saat dilimini İstanbul yaptık

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# --- CANLI YAYIN İÇİN KRİTİK AYAR ---
# Sunucuda 'collectstatic' komutu çalışınca dosyalar buraya toplanacak
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Medya Dosyaları (Resimler vb.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CKEDITOR AYARLARI ---
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 500,
        'width': '100%',
    },
}


# --- JAZZMIN ADMİN PANELİ AYARLARI ---
JAZZMIN_SETTINGS = {
    "site_title": "Artvizyon Panel",
    "site_header": "Artvizyon Yönetim",
    "site_brand": "Gzt. Sami Özçelik",
    "site_logo": None, 
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Haber Merkezi Yönetim Paneli",
    "copyright": "Artvizyon Haber",
    "search_model": "haberler.Haber",
    "topmenu_links": [
        {"name": "🔥 Siteyi Görüntüle", "url": "anasayfa", "permissions": ["auth.view_user"]},
        {"name": "📞 Teknik Destek", "url": "https://wa.me/905320000000", "new_window": True},
    ],
    "order_with_respect_to": [
        "haberler.Haber", 
        "haberler.Kategori", 
        "haberler.Ilce", 
        "haberler.Galeri", 
        "haberler.HaftaninFotografi",
        "haberler.EczaneLinki"
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "haberler.Haber": "fas fa-newspaper",
        "haberler.Kategori": "fas fa-tags",
        "haberler.Ilce": "fas fa-map-marker-alt",
        "haberler.Galeri": "fas fa-images",
        "haberler.GaleriResim": "fas fa-image",
        "haberler.HaftaninFotografi": "fas fa-camera-retro",
        "haberler.EczaneLinki": "fas fa-clinic-medical",
        "haberler.Yorum": "fas fa-comments",       # Yorum ikonu
        "haberler.Destekci": "fas fa-hand-holding-heart", # Destekçi ikonu
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": True, 
}

# --- RENK VE TEMA AYARLARI ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "theme": "sandstone", 
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}